import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Wrapper = styled.header`
  background-color: lightblue;
  height: 50px;
  width: 50px;
`;

const Footer = styled.footer`
  background-color: lightcoral;
  display: flex;
  height: 60px;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App asfd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>Hello Mar'suv</Wrapper>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </Footer>
    </div>
  );
}
